name: 'Run application'
description: 'Prepare local settings and dependencies for running the API with SWA during Playwright tests.'
runs:
  using: 'composite'
  steps:
    - name: Start Cosmos DB emulator
      run: |
        docker run -d \
          -p 8081:8081 \
          -p 10251:10251 \
          -p 10252:10252 \
          -p 10253:10253 \
          -p 10254:10254 \
          -e AZURE_COSMOS_EMULATOR_ACCEPT_EULA=true \
          -e AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10 \
          -e AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true \
          --name cosmos-emulator \
          mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
      shell: bash

    - name: Start SignalR emulator
      run: |
        docker run -d \
          -p 8888:8888 \
          --name signalr-emulator \
          mcr.microsoft.com/azure-signalr/signalr-emulator:latest
      shell: bash

    - name: Wait for emulators
      run: |
        for i in {1..30}; do
          cosmos_ready=$(curl -k -sSf https://localhost:8081/_explorer/index.html > /dev/null && echo yes || echo no)
          signalr_ready=$(curl -sSf http://localhost:8888/api/v1/health > /dev/null && echo yes || echo no)
          if [ "$cosmos_ready" = "yes" ] && [ "$signalr_ready" = "yes" ]; then
            echo "Cosmos DB and SignalR emulators are responding."
            exit 0
          fi
          sleep 2
        done
        echo "Emulators did not become ready in time."
        exit 1
      shell: bash

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install Azure Functions Core Tools
      env:
        NPM_CONFIG_USERCONFIG: /dev/null
      run: npm install -g azure-functions-core-tools@4 --unsafe-perm true --ignore-scripts --registry=https://registry.npmjs.org
      shell: bash

    - name: Restore API dependencies
      run: dotnet restore ./api/api.csproj
      shell: bash

    - name: Create local settings for Functions
      run: |
        cat > ./api/local.settings.json <<'EOF'
        {
          "IsEncrypted": false,
          "Values": {
            "AzureWebJobsStorage": "UseDevelopmentStorage=true",
            "AzureWebJobsSecretStorageType": "Files",
            "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated",
            "CosmosDbConnectionString": "AccountEndpoint=https://localhost:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==",
            "CosmosDbDatabaseId": "GroceryListDb",
            "CosmosDbContainerId": "Items",
            "AzureSignalRConnectionString": "Endpoint=http://localhost:8888;AccessKey=local-dev-key;Version=1.0;"
          },
          "Host": {
            "CORS": "http://localhost:4280,http://localhost:5173,http://127.0.0.1:5173"
          }
        }
        EOF
      shell: bash

    - name: Start SWA CLI
      run: |
        nohup npx swa start http://localhost:5173 --api-location ./api --run "npm run dev:frontend" --port 4280 > ./swa.log 2>&1 &
      shell: bash

    - name: Wait for local app
      run: |
        for i in {1..30}; do
          if curl -sSf http://localhost:4280 > /dev/null; then
            echo "Local app is responding."
            exit 0
          fi
          sleep 2
        done
        echo "Local app did not become ready in time."
        exit 1
      shell: bash
